apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: loadgenerator-autoscale
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: loadgenerator-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50