apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: loadgenerator-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
      - name: loadgenerator
        image: odestanoglu/loadgenerationservice:1.3
        ports:
        - containerPort: 4000
          hostPort: 59999
        livenessProbe:
            httpGet:
                path: /probe/health
                port: 4000
            initialDelaySeconds: 15
            periodSeconds: 5
        resources:
          limits:
            cpu: "1000m"