apiVersion: v1
kind: Pod
metadata:
  name: loadgenerator
  labels:
  	app: loadgenerator
spec:
  containers:
  - name: loadgenerator
    image: odestanoglu/loadgenerationservice:1.2
    ports:
    - containerPort: 80
    livenessProbe:
        httpGet:
            path: /probe/health
            port: 80
        initialDelaySeconds: 15
        periodSeconds: 5
        