apiVersion: v1
kind: Pod
metadata:
  name: loadgenerator
  labels:
  	app: loadgenerator
spec:
  containers:
  - name: loadgenerator
    image: odestanoglu/loadgenerationservice:1.0
    ports:
    - containerPort: 80