apiVersion: v1
kind: Service
metadata:
  name: loadgenerator-service
spec:
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    nodePort:32000
  selector:
    app: loadgenerator
  type: LoadBalancer